networks:
  backend:
    external: true
volumes:
  config_vol:
    
services:
  server:
    image: linuxserver/code-server:latest
    restart: unless-stopped
    # privileged: true
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 120m
    networks:
      backend:
        aliases:
          - codeserver
    volumes:
      - config_vol:/config
      - ${CONFIG_DIR}/config/data/User:/config/data/User
      - ${CONFIG_DIR}/code-server-custom-scripts:/custom-cont-init.d:ro
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: Europe/Oslo
      LC_ALL: nb_NO.UTF-8
      HASHED_PASSWORD: ${HASHED_PASSWORD}
      SUDO_PASSWORD_HASH: ${SUDO_PASSWORD_HASH}
      INSTALL_PACKAGES: lz4|bash|language-pack-nb-base
      DOCKER_MODS: linuxserver/mods:universal-package-install|linuxserver/mods:code-server-php-cli|linuxserver/mods:code-server-nodejs|linuxserver/mods:code-server-extension-arguments|linuxserver/mods:code-server-zsh
      VSCODE_EXTENSION_IDS: github.vscode-github-actions|nonoroazoro.syncing|ms-azuretools.vscode-docker|ms-vscode.azurecli|streetsidesoftware.code-spell-checker-norwegian-bokmal
      PHP_VERSION: 8.4
      PHP_EXTENSIONS: gd|opcache|curl|xml|zip|intl|bcmath|igbinary|redis|mbstring|mcrypt|bz2|dom|pdo|mysql|pgsql|odbc|sqlite3
      ENABLE_COMPOSER: yes
      NODEJS_MOD_VERSION: 23
      SHELL: /usr/bin/zsh
    expose:
      - 8443
    labels:
      traefik.enable: true
      traefik.http.routers.codeserver.rule: Host(`${CODE_HOSTNAME}`)
      traefik.http.routers.codeserver.entrypoints: https
      traefik.http.routers.codeserver.tls: true
      com.centurylinklabs.watchtower.enable: true
      no.dibk.description: 'Kjøres under traefik med entrypoint https for å automatisk mappes opp mot tls'
