services:
  ui:
    image: linuxserver/code-server
    restart: unless-stopped
    ports:
      - ${PORT}:8443
    volumes:
      - ./config:/config
      - ../:/config/workspace
      - ./KeyboardLayout.json:/config/data/User/KeyboardLayout.json:ro
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: Europe/Oslo
      LC_ALL: nb_NO.UTF-8
      LANG: nb_NO.UTF-8
      HASHED_PASSWORD: ${HASHED_PASSWORD}
      SUDO_PASSWORD_HASH: ${SUDO_PASSWORD_HASH}
      DEFAULT_WORKSPACE: /config/workspace
      INSTALL_PACKAGES: language-pack-nb-base
      PHP_VERSION: 8.3
      DOCKER_MODS: linuxserver/mods:universal-package-install|linuxserver/mods:code-server-php-cli|linuxserver/mods:code-server-nodejs|linuxserver/mods:code-server-python3|linuxserver/mods:code-server-zsh
      PHP_EXTENSIONS: gd|imagick|opcache|mysqlnd|curl|xml|zip|intl|bcmath|redis|mbstring|dom
      ENABLE_COMPOSER: yes
      NODEJS_MOD_VERSION: 20
      ZSH_DISABLE_COMPFIX: true
      VSCODE_EXTENSION_IDS: MrChetan.laravel-extension-pack|ms-azuretools.vscode-docker|ms-vscode.azurecli|atlassian.atlascode

