services:
  code-server:
    container_name: code-server
    image: linuxserver/code-server:latest
    restart: unless-stopped
    ports:
      - 8443:8443
    volumes:
      - ./config:/config
    environment:
      PUID: 1026
      PGID: 65538
      TZ: Europe/Oslo
      HASHED_PASSWORD: $$argon2i$$v=19$$m=4096,t=3,p=1$$ty9xAakG9bnq50EkuTpFMw$$9bSQUVXHuJF4/2kHB0d20wsVTWEjWnSFio42VRp862Y
      SUDO_PASSWORD: nqhT2wQ_D%xFJaCfQ6*kA
      PROXY_DOMAIN: code-ew.lan.dibk.no
      DEFAULT_WORKSPACE: /config/workspace
    labels:
      com.centurylinklabs.watchtower.enable: true
