name: Maintenance

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: "58 22 * * 5"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  maintenance:
    # The type of runner that the job will run on
    runs-on:
      - self-hosted
      - mac-4

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Update code-server
        run: |
          cd ${HOME}/Documents/code-server
          podman compose pull
          podman compose up -d
